### PR TITLE
Changing Log Levels of SLFJ-Simple via properties

### PR DESCRIPTION
**Pull request by tariq1890**
- While I wasn't able to find a way to toggle logging. We can still change the logging levels. 
- SLF4j-simple has an implementation where it automatically checks for properties in a file named simplelogger.properties. (It also checks System proeprties, But I thought this was a better approach)
- I have currently set the logging level to Error. In this level, only the logs pertaining to error sceanrios get printed on the server. If our application runs fine, Then is as good as no logging :)

### CODE REVIEW

**Comment by junghuk** [comment]
@tariq1890 can you tell me other logging options,
or link to webpage, which explains that?

**Comment by tariq1890** [comment]
Sure @junghuk , Please refer to this link for more info http://www.slf4j.org/faq.html#requirements.

Right now In Tacoco  slf4j-simple is being used .  The other options I know of are log4j and jdk logs

**Comment by junghuk** [comment]
The six logging levels used by Log are (in order):

trace (the least serious)
debug
info
warn
error
fatal (the most serious)

**Comment by tariq1890** [comment]
Yes !. I have set it to Error. So the logging will be very minimal :). We can set it to TRACE if we want to debug any issues we face in MavenEmbedder!

**Pull request merged**
