### PR TITLE
Tacoco runner

### PR DESCRIPTION
**Pull request by junghuk**

### CODE REVIEW

**Comment by VijayKrishna** [comment]
This is a crack at implementing test-runner for junit test-classes that enable the monitoring of the test-execution on a per-test-case basis using the TacocoListener. This pull request is in response to Issue #10.

**Comment by VijayKrishna** [comment]
@junghuk why do you need to export the paths of tacoco's classes and test-classes to the classpath, i.e. why do you need this command: `export CLASSPATH={tacoco project absolute path}/target/test-classes:{tacoco project absolute path}/target/classes:$CLASSPATH`

And also, what does this command do: `mvn dependency:copy-dependencies -DoutputDirectory=lib`. i just ran it and all it did was that it copied tacoco's dependencies (jar files) into a new folder called lib, that did not exist before. Am i correct? If I am, why are we doing this?

**Comment by junghuk** [comment]
Answers,
- To run TacocoRunner class using java command, we need to do one of followings,
  1. export classpath = tacoco.jar file
  2. export classpath = tacoco classes folder
  3. run java command in the tacoco's classes folder
  
  I choose second one, and I just noticed that test-classes folder is not required to export.
- To execute TacocoRunner with jacoco agent, we need to specify the location of jacoco.jar file. jacoco.jar file is stored in local maven repo because it is specified by tacoco's pom.xml. The script "mvn dependency:copy-dependencies -DoutputDirectory=lib" copies jacoco.jar file(including other jars) from local maven repo to new lib folder. Then I can run this java command,
  "java -javaagent:lib/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=jacoco.exec,dumponexit=false org.spideruci.tacoco.TacocoRunner {your project absolute path}/target/test-classes"

**Comment by VijayKrishna** [comment]
@junghuk, i have merged and deleted the TacocoRunner branch, after an exploratory test session. Please refer to `notes.md` for detailed notes on the exploratory test session i carried out with SourceSurfer.

**Pull request merged**
